# Generated by Django 4.2.1 on 2023-06-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='jhkjglds', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
